'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DockPanel2005.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property DockPaneCaption_AutoHideNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_AutoHideNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneCaption_AutoHideYes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_AutoHideYes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneCaption_CloseDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_CloseDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneCaption_CloseEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_CloseEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneCaption_OptionsDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_OptionsDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneCaption_OptionsEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneCaption_OptionsEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Hide.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipAutoHide() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipClose() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window Position.
        '''</summary>
        Friend ReadOnly Property DockPaneCaption_ToolTipOptions() As String
            Get
                Return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_CloseDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_CloseDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_CloseEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_CloseEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_OptionsDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_OptionsDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_OptionsEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_OptionsEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_OverflowDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_OverflowDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DockPaneStrip_OverflowEnabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DockPaneStrip_OverflowEnabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property DockPaneStrip_ToolTipClose() As String
            Get
                Return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active Files.
        '''</summary>
        Friend ReadOnly Property DockPaneStrip_ToolTipOptions() As String
            Get
                Return ResourceManager.GetString("DockPaneStrip_ToolTipOptions", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
