//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noxa.Emulation.Psp.Player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noxa.Emulation.Psp.Player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] IconBackground {
            get {
                object obj = ResourceManager.GetObject("IconBackground", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InvalidIcon {
            get {
                object obj = ResourceManager.GetObject("InvalidIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MemoryStickIcon {
            get {
                object obj = ResourceManager.GetObject("MemoryStickIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsIcon {
            get {
                object obj = ResourceManager.GetObject("OptionsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseIcon {
            get {
                object obj = ResourceManager.GetObject("PauseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] PspBoot {
            get {
                object obj = ResourceManager.GetObject("PspBoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon PspIcon {
            get {
                object obj = ResourceManager.GetObject("PspIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PspShake {
            get {
                object obj = ResourceManager.GetObject("PspShake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RestartIcon {
            get {
                object obj = ResourceManager.GetObject("RestartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SelectedMemoryStickIcon {
            get {
                object obj = ResourceManager.GetObject("SelectedMemoryStickIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SelectedUmdIcon {
            get {
                object obj = ResourceManager.GetObject("SelectedUmdIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartIcon {
            get {
                object obj = ResourceManager.GetObject("StartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopIcon {
            get {
                object obj = ResourceManager.GetObject("StopIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] UmdIcon {
            get {
                object obj = ResourceManager.GetObject("UmdIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper01 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper02 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper03 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper04 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper05 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper06 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper07 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper07", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper08 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper08", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper09 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper09", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper10 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper11 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wallpaper12 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper12", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
